"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "./[locale]/context";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import Error from "./[locale]/500";

// Can be imported from a shared config
const locales = ["en", "de"];

export default function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	if (!locales.includes(locale)) Error({ statusCode: 404 });

	return (
		<html lang={locale}>
			<AuthProvider>
				<body className={inter.className + " min-h-screen"}>
					{children}
				</body>
			</AuthProvider>
			<ToastContainer />
		</html>
	);
}
