
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInVzZXJuYW1lIjoicGF1bGFvQHBhdWxvLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzAwODc0NDYyLCJleHAiOjE3MDY5MjI0NjJ9.km9Slq9VZX9s25UdbzBM1k2DQaraxi3deIYkt-vDYkI
@URL= http://localhost:3050


POST {{URL}}/auth/signup
Content-Type: application/json

{
    "email": "paulo@paulo.com",
    "password": "paulo",
    "document": "123456789",
    "wallet": "0x0",
    "firstName": "Paulo",
    "lastName": "Evangelista"
}


###
POST {{URL}}/auth/login
Content-Type: application/json

{
    "email": "paulao@paulo.com",
    "password": "paulo"
}



###
GET {{URL}}/auth/test
Authorization: Bearer {{TOKEN}}

###

GET {{URL}}/auth/testAdmin
Authorization: Bearer {{TOKEN}}


###

GET {{URL}}/auth/makeAdmin/id
Authorization: Bearer {{TOKEN}}

